<?php
/**
 * EmbedLRMI
 * Embed LRMI metadata for Articles
 *
 * PHP version 5.4
 *
 * @category Extension
 * @package  EmbedLRMI
 * @author   Jan Böhme <jan@idea-sketch.com>
 * @license  GPL http://www.gnu.org/licenses/gpl.html
 * @link     https://idea-sketch.com
 */

namespace MediaWiki\Extension\EmbedLRMI;

use OutputPage;
use Title;

if (!defined('MEDIAWIKI')) {
  echo("This is a Mediawiki extension and doesn't provide standalone functionality\n");
  die(1);
}

class LRMIData {
  /**
   * @var static LRMIData instance to use for Singleton pattern
   */
  private static $instance;

  /**
   * @var Title current instance of Title received from global $wgTitle
   */
  private $title;

  /**
   * @var string Site name received from global $wgSitename
   */
  private $sitename;

  /**
   * @var string Server URL received from global $wgServer
   */
  private $server;

  /**
   * @var string Repository endpoint
   */
  private $endpoint;

  /**
   * @var string current page/article URL
   */
  private $pageUrl;

  /**
   * @var string lrmi data for current page/article
   */
  private $lrmidata;

  /**
   * Singleton pattern getter
   *
   * @return LRMIData
   */
  public static function getInstance() {
    if(!isset(self::$instance)) {
      self::$instance = new LRMIData();
    }

    return self::$instance;
  }

  /**
   * Class constructor
   */
  public function __construct() {
    global $wgServer, $wgSitename, $wgTitle;

    $this->title = $wgTitle;
    $this->sitename = $wgSitename;
    $this->server = $wgServer;
    $this->endpoint = 'https://repository.staging.openeduhub.net/edu-sharing/rest/search/v1/queries/-home-/mds_oeh/ngsearch/lrmi?contentType=ALL&maxItems=10&skipCount=0';
    $this->pageUrl = str_replace( ['idea-sketch.com','_'], ['zum.de','%20'], $this->title->getFullURL() ); //'https://klexikon.zum.de/wiki/Ada%20Lovelace';
  }

  /**
   * Return creation time or 0 from current Article
   *
   * @return int
   */
  public function getCTime() {
    $ctime = \DateTime::createFromFormat('YmdHis', $this->title->getEarliestRevTime());
    if($ctime) {
      return $ctime->format('c');
    }
    return 0;
  }

  /**
   * Return modification time or 0 from current Article
   *
   * @return int
   */
  public function getMTime() {
    $mtime = \DateTime::createFromFormat('YmdHis', $this->title->getTouched());
    if($mtime) {
      return $mtime->format('c');
    }
    return 0;
  }


  /**
   * Get metadata from EduSharing 
   *
   */  
  private function getMetaData() {

/*     $curl = curl_init( $this->endpoint );
    curl_setopt( $curl, CURLOPT_URL, $this->endpoint );
    curl_setopt( $curl, CURLOPT_POST, true);
    curl_setopt( $curl, CURLOPT_RETURNTRANSFER, true);
    
    $headers = array(
       "accept: application/json",
       "Content-Type: application/json",
    );
    curl_setopt($curl, CURLOPT_HTTPHEADER, $headers);
    
    $data = <<<DATA
    {
     "criteria": [
       {
          "property": "ccm:wwwurl",
            "values": [
              ". $this->pageUrl ."
            ]
        }
     ]
    }
    DATA;
    
    curl_setopt($curl, CURLOPT_POSTFIELDS, $data);

    curl_setopt($curl, CURLOPT_VERBOSE, true);
    $streamVerboseHandle = fopen('php://temp', 'w+');
    curl_setopt($curl, CURLOPT_STDERR, $streamVerboseHandle);
    

    //for debug only!
    //curl_setopt($curl, CURLOPT_SSL_VERIFYHOST, false);
    //curl_setopt($curl, CURLOPT_SSL_VERIFYPEER, false);
    
    $result = curl_exec($curl);
if ($result === FALSE) {
    printf("cUrl error (#%d): %s<br>\n",
           curl_errno($curl),
           htmlspecialchars(curl_error($curl)))
           ;
}

rewind($streamVerboseHandle);
$verboseLog = stream_get_contents($streamVerboseHandle);

echo "cUrl verbose information:\n", 
     "<pre>", htmlspecialchars($verboseLog), "</pre>\n";
    var_dump(curl_getinfo($curl));
    curl_close($curl);

    var_dump($result);die();

    // Maybe we want to set some stuff by ourselves?
    /*
    $mtime = $this->getMtime();

    $created_timestamp = $this->getCTime();
    $modified_timestamp = $this->getMTime();

    $first_revision = $this->title->getFirstRevision();
    if($first_revision) {
      $author = $first_revision->getUserText();
    } else {
      $author = 'None';
    }
    */

// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
$ch = curl_init();

curl_setopt($ch, CURLOPT_URL, 'https://repository.staging.openeduhub.net/edu-sharing/rest/search/v1/queries/-home-/mds_oeh/ngsearch/lrmi?maxItems=10&skipCount=0&propertyFilter=-all-');
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_POST, 1);
$postfields = "{\n \"criteria\": [\n   {\n     \"property\": \"ccm:wwwurl\",\n     \"values\": [\n       \"{$this->pageUrl}\"\n     ]\n   }\n ]\n}";
curl_setopt($ch, CURLOPT_POSTFIELDS, $postfields);

$headers = array();
$headers[] = 'Content-Type: application/json';
$headers[] = 'Accept: application/json';
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

$result = curl_exec($ch);

curl_close($ch);

    if ( $result ) {
      $this->lrmidata = json_decode($result, true);
    }
  }


  function generateTree($data) {

    if ( !is_array( $data ) ) {
      $data = json_decode( $data, true );
    }
    
    $html = '<div><ul>';
    foreach ($data as $key => $value) {
        if (is_array($value)) {
            $html .= '<li><b>' . $key . '</b>: ';
            $html .= $this->generateTree($value);
            $html .= '</li>';
        } else {
            $html .= '<li><b>' . $key . '</b>: ' . $value . '</li>';
        }
    }
    $html .= '</ul></div>';
    return $html;
}



  /**
   * Render head item with LRMI metadata
   *
   * @param OutputPage OutputPage instance referencce
   */
  function render(OutputPage &$out) {
    if($this->title instanceof Title && $this->title->isContentPage()) {

      $this->getMetaData();

      if ( $this->lrmidata ) {
        $out->addHeadItem(
            'LRMIData',
            '<script type="application/ld+json">' . json_encode($this->lrmidata['nodes'][0]) . '</script>'
        );

        $out->addHTML( '<h2><span class="mw-headline">LRMI Metadaten von EduSharing</span></h2><ul>' );
        $out->addHTML( $this->generateTree( $this->lrmidata['nodes'][0]) );
      }
    }
  }
}

?>
